stages:
  - vault

# Based on the examples from https://docs.gitlab.com/ee/ci/examples/authenticating-with-hashicorp-vault/
Vault Authentication and Read Secret:
  stage: vault
  image:
    name: vault:1.9.0
  script:
    # VAULT_ADDR and VAULT_NAMESPACE are set in env vars in
    #  Settings > CI/CD
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/gitlab/login role=app-pipeline jwt=$CI_JOB_JWT)"
    - vault read --field=display_name auth/token/lookup-self
